### ISSUE TITLE
refactor code

### ISSUE THREAD

**Issue by finalight** [finalight/tictactoe-server#1]
need to change this code to fully conform to ES6 practises and style

**Comment by tealiie** [comment]
Hi, I have forked this over and refactoring now.

**Comment by bhalash** [comment]
#2 resolves this ticket:

* Moved script code to ES6.
* Broke up monolithic solution-checking function into discrete functional components that can accept a Tic-tac-toe board of arbitrary size. :)
* Added ESLint to enforce ES6 syntax in a Node environment.
* Cleaned up formatting.
* Added JSDoc-style block comments.
